## NumPy

 - NumPy (Numerical Python) is a Python library that focuses on scientific computing. 
 - NumPy has the ability to create N-dimensional array objects, which are similar to lists in Python. 
 - The advantage of NumPy arrays compared to lists in Python is that they consume less memory and run time faster. 
 - NumPy also makes it easier for us in Linear Algebra, especially operations on Vectors (1-d arrays) and Matrix (2-d arrays).

In [1]:
# import NumPy

import numpy as np

In [2]:
# Checking NumPy Version

print(np.__version__)

1.24.3


In [3]:
# creating a NumPy array

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# Use a tuple to create a NumPy array

import numpy as np

arr = np.array((1,2,3,4,5))

print(arr)

[1 2 3 4 5]


In [6]:
import numpy as np

arr = np.array(["Data Analyst", "MyEduSolve", "Kampus Merdeka"])

print(arr)

print(type(arr))

['Data Analyst' 'MyEduSolve' 'Kampus Merdeka']
<class 'numpy.ndarray'>


### Dimensions in Arrays

A dimension in arrays in one level of array depth (nested arrays).

In [7]:
# 0-D Array

import numpy as np

arr = np.array(42)

print(arr)

42


In [8]:
# Creating a 1-D array

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [9]:
# Creating a 2-D array

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# Creating a 3-D array

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
# 0-D Array string

import numpy as np

arr = np.array("Data Analyst")

print(arr)

Data Analyst


In [12]:
# Creating a 1-D array integer, float, string

import numpy as np

arr = np.array([6, 7.8, "Sembilan"])

print(arr)

['6' '7.8' 'Sembilan']


In [13]:
# Creating a 2-D array

import numpy as np

arr = np.array([[1, 2.3], [4.5, "Enam"]])

print(arr)

[['1' '2.3']
 ['4.5' 'Enam']]


In [14]:
# Check how many dimensions the arrays have

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [15]:
# Create an array with 5 dimensions and verify that it has 5 dimensions

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [16]:
# Get the first element from the following array

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [17]:
# Get the second element from the following array

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [18]:
# Get third and fourth elements from the following array and add them

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] * arr[3])

12


In [19]:
# Access the element on the first row, second column

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [20]:
# Access the element on the 2nd row, 5th column

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [21]:
# Task

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])

print(arr[0,2] * arr[1,1])
print('3rd element on 3rd row: ', arr[2, 2])

21
3rd element on 3rd row:  13


In [22]:
# Access the third element of the second array of the first array

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[1, 0, 2])

9


In [23]:
# Print the last element from the 2nd dimension

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dimension: ', arr[1, -1])

Last element from 2nd dim:  10
